services:
  # Apache PHP - Producto 2
  apache-php-p2:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: apache-php-p2
    restart: always
    volumes:
      - ./www:/var/www/html
    ports:
      - "8090:80"
    depends_on:
      - db-p2

  # Base de Datos - Producto 2
  db-p2:
    image: mysql:8.0
    container_name: mysql-db-p2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: reparaya
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data_p2:/var/lib/mysql

  # Laravel - Producto 2
  laravel-app-p2:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: laravel-app-p2
    restart: always
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "8092:80"
    depends_on:
      - db-p2

  # PhpMyAdmin - Producto 2
  phpmyadmin-p2:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-p2
    restart: always
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db-p2
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - db-p2

  # WordPress - Producto 2
  wordpress-p2:
    image: wordpress:latest
    container_name: wp-p2
    restart: always
    ports:
      - "8095:80"
    environment:
      WORDPRESS_DB_HOST: wp_db_p2
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - wp_db_p2

  # BD WordPress - Producto 2
  wp_db_p2:
    image: mysql:8.0
    container_name: wp_db_p2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - wp_db_data_p2:/var/lib/mysql

volumes:
  db_data_p2:
  wp_db_data_p2: